server:
  port: 8888
  servlet:
    context-path: /config
spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/psramkumar/spring-config.git
          searchPaths: '{application}'
          basedir: userhome/cfgservrepo
          skipSslValidation: true
          refreshRate: 300
